### PR TITLE
Add a few more Netscaler options

### PR DESCRIPTION
**Pull request by schaefferp**
This pull request consists of a few more API options :

lbvserver : 
- appflowlog

servicegroup :
- cka
- cip
- usip
- useproxyport
- tcpb
- cmp
- cipheader

lbmonitor :
- send
- recv
- lrtm
- interval
- resptimeout
- retries

And also a fix for checking IP/td/port before IP/td/servicetype (commit cb09072 is commented)

### CODE REVIEW

**Comment by jmcgill298** [comment]
@schaefferp Thanks for your contributions; I will take a closer look and validate with some testing as soon as I get some time.

**Review by jmcgill298 — CHANGES_REQUESTED** [review]
@schaefferp it seems like the servicetype should not be in consideration at all in checking for duplicates. I have merged a fix for this in the most recent pull request that only checks for IP, Traffic Domain, and Port. The merge also includes an additional param that allows for changing the IP and Name when set to True.

Can you look at this and verify this fixes the issue, and if it does, can you remove these changes?

**Comment by schaefferp** [comment]
I tested successfully after reverting my commit and using your fix (cfc6789)

**Comment by jmcgill298** [comment]
@schaefferp Sorry this took so long. Since it was waiting on me for so long, I made the necessary updates to match our naming style. I aliased all names that were changed, so that the parameter names you used are still valid (didn't want to break anything you have been using). 

I also removed the defaults that you had set because we that might cause unexpected behavior when objects are involved in subsequent tasks or task executions. 

I have also updated unittests to include these parameters.

**Pull request merged**
